version: '3'

services:
  mlflow:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow/artifacts:/mlflow/artifacts
      - ./mlflow/logs:/mlflow/logs
      - ./mlflow/db:/mlflow/db
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_SERVE_ARTIFACTS=true
    restart: unless-stopped
